main : ${project.groupId}.essence.Essence
name: Essence
version: ${project.version}
description: ${project.description}
website: ${project.url}
author: ${project.author}
authors: ${project.authors}
depend: [EssenceCore]
softdepend: [Vault]